perfetto_cmd: Resolve missing O_CREAT mode
 src/perfetto_cmd/perfetto_cmd.cc:359:65:
  error: 'open' has superfluous mode bits; missing O_CREAT?

Thanks to @AdrianDC and this: https://github.com/LineageOS/android_external_perfetto/commit/b73bf8234463820a9fd3ae31be90441fde99f3ac